[package]
name = "shared_sql_utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstr = { path = "../cstr" }
thiserror = { workspace = true }
constants = { path = "../constants" }
